gfx/env/dustBK.tga
gfx/env/dustDN.tga
gfx/env/dustFT.tga
gfx/env/dustLF.tga
gfx/env/dustRT.tga
gfx/env/dustUP.tga
gfx/detail/dt_brick.tga
gfx/detail/dt_carpet1.tga
gfx/detail/dt_conc.tga
gfx/detail/dt_fabric1.tga
gfx/detail/dt_fabric2.tga
gfx/detail/dt_grass1.tga
gfx/detail/dt_ground1.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_ground4.tga
gfx/detail/dt_ground5.tga
gfx/detail/dt_leather1.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_plaster1.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_rock1.tga
gfx/detail/dt_rough1.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_smooth2.tga
gfx/detail/dt_snow.tga
gfx/detail/dt_snow1.tga
gfx/detail/dt_snow2.tga
gfx/detail/dt_ssteel1.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_stone4.tga
gfx/detail/dt_wood.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/detail/dt_wood3.tga
maps/de_sandtemple.bsp
maps/de_sandtemple.txt
maps/de_sandtemple_detail.txt
overviews/de_sandtemple.bmp
overviews/de_sandtemple.txt
sound/ambience/mechwhine.wav
